[workspace]
members = [
	".",
	"members/criterion_ex",
	"members/revsqrt",
	"members/serde-json-demo",
	"members/slog-demo",
]
default-members = [
	".",
	"members/criterion_ex",
	"members/revsqrt",
	"members/serde-json-demo",
	"members/slog-demo",
]

[package]
name = "rs-basic"
version = "0.2.0"
edition = "2021"
authors = ["Christoph J. Scherr <softwar@cscherr.de>"]
publish = false
autobins = true
default-run = "rs-basic"
