[workspace]
members = [
  ".",
  "members/criterion-demo",
  "members/cucumber-demo",
  "members/revsqrt",
  "members/serde-json-demo",
  "members/slog-demo",
]
default-members = [
  ".",
  "members/criterion-demo",
  "members/revsqrt",
  "members/serde-json-demo",
  "members/slog-demo",
  "members/cucumber-demo",
]

[package]
name = "rs-basic"
version = "0.2.0"
edition = "2021"
authors = ["Christoph J. Scherr <softwar@cscherr.de>"]
publish = false
autobins = true
default-run = "rs-basic"
