[workspace]
members = [
  ".",
  "members/criterion-demo",
  "members/cucumber-demo",
  "members/panic-calm",
  "members/pest-demo",
  "members/revsqrt",
  "members/serde-json-demo",
  "members/slog-demo",
  "members/socker",
  "members/tokryon",
]
default-members = [
  ".",
  "members/revsqrt",
  "members/criterion-demo",
  "members/pest-demo",
  "members/serde-json-demo",
  "members/slog-demo",
  "members/cucumber-demo",
  "members/panic-calm",
  "members/socker",
  "members/tokryon",
]

[package]
name = "rs-basic"
version = "0.2.1"
edition = "2021"
authors = ["Christoph J. Scherr <softwar@cscherr.de>"]
publish = false
autobins = true
default-run = "rs-basic"
