[workspace]
publish = false
members = [
	".",
]
default-members = [
	".",
]

[package]
name = "rs-basic"
version = "0.1.0"
edition = "2021"
authors = ["Christoph J. Scherr <softwar@cscherr.de>"]
publish = false
autobins = true
default-run = "rs-basic"
