[workspace]
publish = false
members = [
	".", "members/criterion_ex",
	"members/revsqrt",
]
default-members = [
	".",
	"members/revsqrt",
]

[package]
name = "rs-basic"
version = "0.2.0"
edition = "2021"
authors = ["Christoph J. Scherr <softwar@cscherr.de>"]
publish = false
autobins = true
default-run = "rs-basic"
