[package]
name = "fluent-webserv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
fluent = "0.16.0"
rocket = "0.5.0"
unic-langid = "0.9.4"
