name: Cargo Check and Test
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check  --all-features --verbose
      - run: cargo test   --all-features --verbose
